<xacro:macro name="link_box" params="link_name length width height density:=1 mesh_name:='nofile' *origin_vis *origin_col *origin_inertial">
  <xacro:property name="mass" value="${length*height*width*density}" />
  <link name="${link_name}">
    <visual>
      <!-- <origin xyz="0 0 0" rpy="0 0 0"/> -->
      <xacro:insert_block name="origin_vis" />
      <geometry>
        <xacro:if value="${mesh_name == 'nofile'}">
          <box size="${length} ${width} ${height}"/>
        </xacro:if>
        <xacro:unless value="${mesh_name == 'nofile'}">
          <mesh filename="${mesh_name}" />
        </xacro:unless>
      </geometry>
    </visual>
    <collision>
      <!-- <origin xyz="0 0 0.0" rpy="0 0 0"/> -->
      <xacro:insert_block name="origin_col" />
      <geometry>
        <box size="${length} ${width} ${height}"/>
      </geometry>
    </collision>
    <inertial>
      <!-- <origin xyz="0 0 0" rpy="0 0 0"/> -->
      <xacro:insert_block name="origin_inertial" />
      <mass value="${mass}"/>
      <inertia
        ixx="${mass*(pow(height,2) + pow(width,2))/12}" ixy="0.0" ixz="0.0"
        iyy="${mass*(pow(length,2) + pow(height,2))/12}" iyz="0.0"
        izz="${mass*(pow(length,2) + pow(width,2))/12}"/>
    </inertial>
  </link>
</xacro:macro>
