<?xml version='1.0'?>

<robot name="mobile_manipulator_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <gazebo>
    <static>true</static>
  </gazebo>

<!--############################### -->
<!-- MOBILE PLATFORM -->
<!--############################### -->
  <origin xyz="0 0 0.15" rpy="0 0 0"/>
  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="mobile_body_link" />
    <origin xyz="0 0 0.0" rpy="0 0 0"/>
  </joint>


  <!-- MOBILE BASE -->
  <!-- ==================================== -->
  <xacro:property name="mobile_body_length" value="0.65" />
  <xacro:property name="mobile_body_width" value="0.4" />
  <xacro:property name="mobile_body_height" value="0.2" />
  <xacro:property name="mobile_body_density" value="1" />
  <xacro:property name="mobile_body_mass" value="${mobile_body_length*mobile_body_height*mobile_body_width*mobile_body_density}" />
  <link name="mobile_body_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://custom_robot_tutorial/meshes/base_mesh.stl" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0.0" rpy="0 0 0"/>
      <geometry>
        <box size="${mobile_body_length} ${mobile_body_width} ${mobile_body_height}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mobile_body_mass}"/>
      <inertia
        ixx="${mobile_body_mass*(pow(mobile_body_height,2) + pow(mobile_body_width,2))/12}" ixy="0.0" ixz="0.0"
        iyy="${mobile_body_mass*(pow(mobile_body_length,2) + pow(mobile_body_height,2))/12}" iyz="0.0"
        izz="${mobile_body_mass*(pow(mobile_body_length,2) + pow(mobile_body_width,2))/12}"/>
    </inertial>
  </link>

  <!-- FRONT LEFT WHEEL -->
  <!-- ==================================== -->
  <xacro:property name="wheel_radius" value="0.1" />
  <xacro:property name="wheel_length" value="0.1" />
  <xacro:property name="wheel_density" value="1" />
  <xacro:property name="wheel_mass" value="${pi*wheel_length*pow(wheel_radius,2)*wheel_density}" />
  <joint type="continuous" name="wheel_front_left_joint">
    <origin xyz="${mobile_body_length/2-wheel_radius-0.025} ${mobile_body_width/2 + wheel_length/2 + 0.005} -${mobile_body_height/4}" rpy="-${pi/2} 0 0"/>
    <child link="wheel_front_left_link"/>
    <parent link="mobile_body_link"/>
    <axis xyz="0 0 1" rpy="0 0 0"/>
    <limit effort="100" velocity="100"/>
  </joint>

  <link name="wheel_front_left_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://custom_robot_tutorial/meshes/wheel_mesh.stl" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${wheel_mass}"/>
      <inertia
        ixx="${wheel_mass*(3*pow(wheel_radius,2)+pow(wheel_length,2))/12}" ixy="0.0" ixz="0.0"
        iyy="${wheel_mass*(3*pow(wheel_radius,2)+pow(wheel_length,2))/12}" iyz="0.0"
        izz="${wheel_mass*pow(wheel_radius,2)/2}"/>
    </inertial>
  </link>
</robot>
